name: Publish to PyPI

on: 
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: python3 -m pip install --user --upgrade setuptools wheel twine
    - name: build package
      run: python3 setup.py sdist bdist_wheel
    - name: publish
      run: python3 -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*
